export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const ADD_API_DATA = 'ADD_API_DATA';
export const TOGGLE_RESULTS_LOADING = 'TOGGLE_RESULTS_LOADING';
export const RESULTS_MESSAGE = 'RESULTS_MESSAGE';
